amzustory9/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('login', views.log_in, name='login'),
    path('logout', views.log_out, name='logout'),
    path('signup', views.sign_up, name='signup'),
]

main/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser

# Create your models here.

main/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


def home(request):
    return render(request, 'main/home.html')

def log_in(request):
    if (request.method == "POST"):
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        success = False
        if user is not None:
            login(request, user)
            success = True
            return render(request, 'main/home.html', {'success':success})
        
        else:
            
            return render(request, 'main/login.html', {'success':success})
    else:  
        return render(request, 'main/login.html')

def log_out(request):
    logout(request)
    return HttpResponseRedirect('/')

def sign_up(request):
    if(request.method == "POST"):
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.create_user(username, email, password)
        user.save()
        return HttpResponseRedirect('/login')
    else:
        return render(request, 'main/signup.html')

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}
<div class="container text-center mt-5 pt-5 mb-5 pb-5">
    {% if user.is_authenticated %}
    <h3>Greetings, {{ user.username }}</h3>
    <p><a href="{% url 'main:logout' %}">Log Out</a></p>
    {% else %}
    <h3>You are not logged in</h3>
    <p><a href="{% url 'main:login' %}">Log In</a></p>
    {% endif %}
{% endblock content %}

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}
<div class="container text-center mt-5 pt-5 mb-5 pb-5">
    <form action="{% url 'main:login' %}" method="post">
        {% csrf_token %}
        <div>
            <h2>Log In</h2>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">
                        <i class="fa fa-key"></i>
                    </span>
                </div>
                <input type="text" placeholder="Username" name="username" id="username">
            </div>
            <br>
            <div class="input-group mb-3">
                <div class="input-group-prepend">
                    <span class="input-group-text" id="basic-addon1">
                        <i class="fa fa-key"></i>
                    </span>
                </div>
                <input type="password" placeholder="Password" name="password" id="password">
            </div>
            <button type="submit" class="btn btn-dark">Log In</button>
            {% if success == False %}
        <p style="color: red;">Login attempt failed. Please make sure you have the correct Username & Password</p>
        <br>
        {% endif %}
        <p>Create an Account <a href="{% url 'main:signup' %}">Sign Up</a></p>
        </div>
    </form>
</div>
{% endblock content %}

main/templates/main/signup.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}
<div class="container text-center mt-5 pt-5 mb-5 pb-5">
    <form action="{% url 'main:signup' %}" method="post">
        {% csrf_token %}
    <div>
        <h2>Create an Account</h2>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
            </div>
            <input type="text" placeholder="Username" name="username" id="username">
        </div>
        <br>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
            </div>
            <input type="email" placeholder="E-mail" name="email" id="email">
        </div>
        <br>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
            </div>
            <input type="password" placeholder="Password" name="password" id="password">
        </div>
        <br>
        <button type="submit" class="btn btn-dark">Sign Up</button>
        <br>
        <p>Already have an account? <a href="{% url 'main:login' %}">Log In</a></p>
    </div>
    </form>
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.1/jquery.min.js"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <div class="jumbotron jumbotron-fluid">
    <div class="container">
      <h1 class="display-4">Story 9</h1>
      <p class="lead">Ammar M. Zufar</p>
    </div>
  </div>
  {% block content %}
  {% endblock content %}
</body>

</html>